import type { ComboInfo } from '../data/bigTwoRules'

export const suitOrder = ['♦ ダイヤ', '♣ クラブ', '♥ ハート', '♠ スペード']

export const rankOrder = ['3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A', '2']

export const comboRanking = [
  'ストレート',
  'フラッシュ',
  'フルハウス',
  'フォーカード',
  'ストレートフラッシュ',
]

export const comboDetails: ComboInfo[] = [
  {
    id: 'straight',
    name: 'ストレート',
    summary: '5枚の連続した数字。スートは混ざっていてもOK。',
    detail:
      'まず一番強い数字を比べ、同じならその一番強いカードのスートを比べます。このアプリのルールでは、2はストレートに使いません。',
    validExample: '4♦ 5♣ 6♥ 7♠ 8♦',
    invalidExample: '10♦ J♣ Q♥ K♠ 2♦',
    tieBreak: '一番強い数字で比較し、同じならそのカードのスートで比較。',
    beats:
      'より強いストレート、または任意のフラッシュ、フルハウス、フォーカード、ストレートフラッシュに負けます。',
    exampleCards: ['4D', '5C', '6H', '7S', '8D'],
  },
  {
    id: 'flush',
    name: 'フラッシュ',
    summary: '同じスート5枚。',
    detail:
      'このルールでは、まずスートを比べます。スートが同じなら一番強い数字を比べ、必要ならその次も比べます。',
    validExample: '3♠ 6♠ 8♠ J♠ A♠',
    invalidExample: '4♥ 7♥ 9♥ Q♦ A♥',
    tieBreak: 'まず高いスート、同じスートなら一番強い数字で比較。',
    beats:
      'より強いフラッシュ、または任意のフルハウス、フォーカード、ストレートフラッシュに負けます。',
    exampleCards: ['3S', '6S', '8S', 'JS', 'AS'],
  },
  {
    id: 'full-house',
    name: 'フルハウス',
    summary: '同じ数字3枚 + 別の同じ数字2枚。',
    detail: 'フルハウス同士では、3枚組の数字だけを比べます。',
    validExample: '9♦ 9♣ 9♠ K♥ K♣',
    invalidExample: '5♦ 5♣ 8♥ 8♠ A♦',
    tieBreak: '3枚組の数字だけで比較。',
    beats: 'より強いフルハウス、または任意のフォーカードかストレートフラッシュに負けます。',
    exampleCards: ['9D', '9C', '9S', 'KH', 'KC'],
  },
  {
    id: 'four-of-a-kind',
    name: 'フォーカード',
    summary: '同じ数字4枚 + 余り1枚。',
    detail: 'キッカーは強さに影響しません。4枚揃っている数字だけを見ます。',
    validExample: 'Q♦ Q♣ Q♥ Q♠ 3♦',
    invalidExample: 'J♦ J♣ J♥ 7♠ 7♦',
    tieBreak: '4枚揃っている数字で比較。',
    beats: 'より強いフォーカード、または任意のストレートフラッシュに負けます。',
    exampleCards: ['QD', 'QC', 'QH', 'QS', '3D'],
  },
  {
    id: 'straight-flush',
    name: 'ストレートフラッシュ',
    summary: '同じスートで5枚連続した数字。',
    detail:
      'このアプリで最強の5枚役です。一番強い数字を比べ、同じならそのカードのスートを比べます。',
    validExample: '5♥ 6♥ 7♥ 8♥ 9♥',
    invalidExample: '6♣ 7♣ 8♣ 9♣ J♣',
    tieBreak: '一番強い数字で比較し、同じならそのカードのスートで比較。',
    beats: 'より強いストレートフラッシュにだけ負けます。',
    exampleCards: ['5H', '6H', '7H', '8H', '9H'],
  },
]

export const content = {
  hero: {
    eyebrow: 'Big 2 Helper',
    title: 'Big 2 Helper',
    cantonese: '鋤大D',
    cantoneseRuby: 'co2 daai6 di2',
    mandarin: '大老二',
    mandarinRuby: 'da lao er',
  },
  tabs: {
    cheatSheet: 'チートシート',
    calculator: '計算機',
  },
  language: {
    label: '言語',
    en: 'English',
    ja: '日本語',
  },
  summary: {
    suitOrder: 'スート順',
    rankOrder: '数字順',
    ascending: '弱い → 強い',
    rankHint: '3が最弱、2が最強',
    validPlays: '有効な出し方',
    quickGuide: 'かんたん確認',
    comboRanking: '5枚役の強さ',
    lowestToHighest: '弱い → 強い',
    handChecker: 'これは役？',
    pickFive: '5枚選ぶ',
  },
  validPlays: {
    singles: 'シングル',
    singlesCopy: '1枚出し。',
    singlesExample: '例: A♠',
    doubles: 'ペア',
    doublesCopy: '同じ数字2枚。',
    doublesExample: '例: 9♦ 9♣',
    triples: 'トリプル',
    triplesCopy: '同じ数字3枚。',
    triplesExample: '例: Q♦ Q♣ Q♥',
    invalidNotePrefix: 'ポーカーと違って、',
    invalidNoteStrong: 'ツーペアは有効な出し方ではありません',
    invalidNoteSuffix: '。',
  },
  handChecker: {
    show: '表示',
    hide: '閉じる',
    clear: 'クリア',
    intro: '5枚ちょうど選ぶと、その場で役を判定します。',
    helper: 'スートごとにまとまっていて、数字は3から2の順です。',
    selectedCount: (count: number) => `${count}/5枚選択`,
    waitingMessage: (count: number) => `5枚選んでください。(${count}/5枚選択)`,
    invalidHand: 'このルールでは有効な5枚役ではありません。',
  },
  comboDetails: {
    exampleHand: '例:',
    validExample: '有効な例',
    invalidExample: '無効な例',
    tieBreak: '同役時の比較',
    beatenBy: 'これに勝つもの',
  },
  rules: {
    title: 'ラウンドの流れ',
    show: '表示',
    hide: '閉じる',
    items: [
      '手札をすべてなくした人が勝ちです。',
      '有効な出し方で、より強い組み合わせが勝ちます。',
      'パスできます。',
      '誰かの手札が0枚になったらラウンド終了です。',
      '精算は残り枚数をもとに行います。',
    ],
  },
  calculator: {
    players: 'プレイヤー',
    winnerCopyPrefix: '勝者は ',
    winnerCopyStrong: '残り0枚',
    winnerCopySuffix: ' のプレイヤーです。',
    name: '名前',
    cardsLeft: '残り枚数',
    playerLabel: (index: number) => `Player ${index + 1}`,
    playerNameAria: (index: number) => `Player ${index + 1} の名前`,
    cardsLeftAria: (name: string) => `${name} の残り枚数`,
    settings: '設定',
    settingsSummary: (valuePerCard: number, unitLabel: string, threshold: number, multiplier: number) =>
      `1枚 ${valuePerCard} ${unitLabel || 'ポイント'}、しきい値 ${threshold}、倍率 ${multiplier}`,
    valuePerCard: '1枚あたりの値',
    unitLabel: '単位',
    penaltyThreshold: 'しきい値',
    penaltyMultiplier: '倍率',
    multiplierCopyPrefix: '支払う側の残り枚数がしきい値以上なら、',
    multiplierCopyStrong: 'その人のすべてのペア精算に倍率がかかります',
    multiplierCopySuffix: '。',
    calculate: '精算する',
    reset: 'リセット',
    checkInputs: '入力を確認してください',
    pairwiseSettlements: 'ペアごとの精算',
    differenceBased: '差分ベース',
    owes: '→',
    netTotals: '合計収支',
    copyResults: '結果をコピー',
    saveResults: '結果を保存',
    savedTotals: '保存した合計',
    runningTotalsCopy: '保存したラウンド名ごとに累計をまとめています。',
    resetAll: 'すべてリセット',
    noSavedRounds: '保存されたラウンドはまだありません。',
    roundHistory: 'ラウンド履歴',
    delete: '削除',
    cardsLeftSuffix: '枚残り',
  },
  feedback: {
    copied: '結果をコピーしました。',
    copyFailed: 'コピーに失敗しました。',
    saved: '結果を保存しました。',
  },
  confirmations: {
    resetHistory: '保存した合計と履歴をすべてリセットしますか？',
    deleteRound: 'このラウンドを履歴と合計から削除しますか？',
  },
  history: {
    player: 'プレイヤー',
    total: '合計',
  },
  misc: {
    bigTwoSettlement: 'Big Two 精算',
    pairwise: 'ペアごと:',
    net: '合計:',
  },
  units: [
    { label: '円 (¥)', value: '¥' },
    { label: 'ポイント', value: 'points' },
    { label: 'ドル ($)', value: '$' },
    { label: 'ポンド (£)', value: '£' },
  ],
  handCheckerSuits: [
    { symbol: '♦', tone: 'red' as const, label: 'ダイヤ' },
    { symbol: '♣', tone: 'black' as const, label: 'クラブ' },
    { symbol: '♥', tone: 'red' as const, label: 'ハート' },
    { symbol: '♠', tone: 'black' as const, label: 'スペード' },
  ],
} as const
